name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    strategy:
      matrix:
        board:
          - fqbn: MightyCore:avr:1284:pinout=standard,variant=modelNonP,BOD=2v7,LTO=Os,clock=16MHz_external
            platforms: |
              - name: MightyCore:avr
                source-url: https://mcudude.github.io/MightyCore/package_MCUdude_MightyCore_index.json
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        id: build
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          sketch-paths: |
            - ./
          libraries: |
            - name: FastLED
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#div-02-robotics-ci'
        if: always()
